apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cicd-ingress.deploy-test01
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: deploy-test-svc
              servicePort: 12345
